[project]
name = "poster-maker"
version = "0.1.1"
description = "Cross-platform poster tiling tool for PDF/images"
requires-python = ">=3.10"
dependencies = [
  "PyMuPDF>=1.24",
]

[project.scripts]
poster-maker = "poster_maker.app_tk:main"
poster-maker-cli = "poster_maker.core:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
